# Generated by Django 5.2.7 on 2025-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=150.0, max_digits=6)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('description', models.TextField(blank=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='movies.genre')),
                ('language', models.ManyToManyField(blank=True, to='movies.language')),
            ],
        ),
    ]
